# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example2
  pod 'Firebase'
  pod 'Firebase/Database'
  
end
